-- Sci-fi conversion, Lua half: apply the rules table in the LOAD context.
--
-- This file is authored. `rules.lua` beside it is generated by
-- tools/scripts/transform.py from tools/rules/naming.csv and must never be
-- edited by hand. Code here, data there.
--
-- Why substitution happens at load time rather than being baked in: the load
-- context runs after every content file, so this reads whatever text is
-- actually in memory - including text another mod changed - and substitutes
-- into it. That is the whole reason the Lua half cannot conflict with a mod
-- list, and precomputing the strings would throw it away.
--
-- API surfaces, verified in the shipped 0.51 stubs before use:
--   resources/lua_api/openmw/content.lua
--     "A mutable list of all BookRecords" -> content.books.records, and the
--     same shape for spells, miscs, ingredients
--     content.gameSettings.records maps id directly to a value, which is why
--     GMST is written as store[id] = value and not rec.field = value
--   resources/lua_api/openmw/types.lua
--     BookRecord: @field name, @field text
-- Both writes were measured on 2026-08-28: BOOK name and BOOK text are
-- writable from here and the result is visible on screen.
--
-- NEVER string.gsub. Its needle is a Lua pattern, in which - . % ( ) [ ] + *
-- ? ^ $ are all special, and it has no plain-match flag. string.find takes one
-- as its fourth argument. The rules table is prose, so this is not a style
-- preference.

local content = require('openmw.content')
local rules = require('scripts.rewrite.rules')

local TAG = '[REWRITE]'

local function log(...)
    local parts = {}
    for i = 1, select('#', ...) do
        parts[i] = tostring((select(i, ...)))
    end
    print(TAG .. ' ' .. table.concat(parts, ' '))
end

local function try(fn)
    local ok, res = pcall(fn)
    if ok then return true, res end
    return false, res
end

----------------------------------------------------------------------------
-- Matching
----------------------------------------------------------------------------

local function isLetter(ch)
    return ch ~= nil and string.match(ch, '%a') ~= nil
end

-- Byte ranges inside pseudo-HTML tags. Everything in a tag is a machine
-- reference: FACE="Daedric" names a FONT, and there are 137 of them across the
-- masters. Substituting there points the page at a font that does not exist.
local function markupSpans(text)
    local spans, i = {}, 1
    while true do
        local a = string.find(text, '<', i, true)
        if a == nil then return spans end
        local b = string.find(text, '>', a, true)
        if b == nil then
            spans[#spans + 1] = { a, #text }
            return spans
        end
        spans[#spans + 1] = { a, b }
        i = b + 1
    end
end

local function inSpans(i, j, spans)
    for _, s in ipairs(spans) do
        if s[1] <= i and j <= s[2] then return true end
    end
    return false
end

-- lower / sentence / title / upper / other, matching the Python classifier
-- exactly. Any disagreement between the two shows up as a diff in the
-- equivalence test, which is why both are written the same way.
local function shape(text)
    local hasLetter = string.match(text, '%a') ~= nil
    if not hasLetter then return 'other' end
    if text == string.lower(text) then return 'lower' end
    if text == string.upper(text) then return 'upper' end

    local words, allTitle, firstTitle, restLower = {}, true, false, true
    for word in string.gmatch(text, '%S+') do
        if string.match(string.sub(word, 1, 1), '%a') then
            words[#words + 1] = word
        end
    end
    if #words == 0 then return 'other' end
    for idx, word in ipairs(words) do
        local head = string.sub(word, 1, 1)
        local tail = string.sub(word, 2)
        local titled = head == string.upper(head) and tail == string.lower(tail)
        if not titled then allTitle = false end
        if idx == 1 then
            firstTitle = titled
        elseif word ~= string.lower(word) then
            restLower = false
        end
    end
    if allTitle then return 'title' end
    if firstTitle and restLower then return 'sentence' end
    return 'other'
end

local function titleCase(text)
    local out = {}
    for word in string.gmatch(text, '%S+') do
        out[#out + 1] = string.upper(string.sub(word, 1, 1)) .. string.sub(word, 2)
    end
    return table.concat(out, ' ')
end

local function cast(replacement, matched, caseMode)
    if caseMode == 'literal' then return replacement end
    local s = shape(matched)
    if s == 'lower' then return string.lower(replacement) end
    if s == 'upper' then return string.upper(replacement) end
    if s == 'title' then return titleCase(replacement) end
    return replacement
end

-- One left-to-right pass per rule. Replacements are validated never to contain
-- any rule's pattern, so a single pass is complete and the result is
-- idempotent.
local function applyRule(value, rule)
    local spans = markupSpans(value)
    local lowValue = string.lower(value)
    local lowPattern = string.lower(rule.pattern)
    local plen = #rule.pattern

    local out, prev, pos, hits = {}, 1, 1, 0
    while true do
        local i = string.find(lowValue, lowPattern, pos, true)
        if i == nil then break end
        local j = i + plen - 1

        local ok = true
        if rule.left and i > 1 and isLetter(string.sub(value, i - 1, i - 1)) then
            ok = false
        end
        if rule.right and j < #value and
                isLetter(string.sub(value, j + 1, j + 1)) then
            ok = false
        end
        if ok and inSpans(i, j, spans) then ok = false end

        if ok then
            local matched = string.sub(value, i, j)
            out[#out + 1] = string.sub(value, prev, i - 1)
            out[#out + 1] = cast(rule.replacement, matched, rule.case)
            prev = j + 1
            hits = hits + 1
        end
        pos = i + 1
    end
    if hits == 0 then return value, 0 end
    out[#out + 1] = string.sub(value, prev)
    return table.concat(out), hits
end

local function applyAll(value, recordId)
    local total = 0
    for _, rule in ipairs(rules.rules) do
        if not (rule.exclude and rule.exclude[string.lower(recordId)]) then
            local hits
            value, hits = applyRule(value, rule)
            total = total + hits
        end
    end
    return value, total
end

----------------------------------------------------------------------------
-- Writing
----------------------------------------------------------------------------

local STORE = {
    BOOK = 'books',
    SPEL = 'spells',
    MISC = 'miscs',
    INGR = 'ingredients',
    GMST = 'gameSettings',
    MGEF = 'magicEffects',
}

local function findRecord(store, id)
    for _, variant in ipairs({ id, string.lower(id) }) do
        local ok, rec = try(function() return store[variant] end)
        if ok and rec ~= nil then return rec, variant end
    end
    return nil, nil
end

-- Light is the one magic effect whose particle texture is not a magic texture.
-- Its record names `tx_firealpha00a`, the world flame sheet that every torch,
-- brazier and campfire in the game also wears, so the texture pack cannot
-- override it: converting one spell would put hexagons on every fire. Instead
-- `make_vfx.py` writes a private copy under a name nothing else uses, and this
-- points the record at it.
--
-- Guarded on purpose. `particle` is documented as a field of MagicEffect and
-- the record list is documented as mutable, but no probe has established that
-- this particular field has a setter in 0.51 - and unlike `name`, it was never
-- part of the WO0 spike. If the engine refuses, Light keeps the vanilla flame
-- and nothing else changes. The log line says which happened.
local LIGHT_EFFECT = 'Light'
local LIGHT_PARTICLE = 'vfx_zen_light.dds'

local function redirectLight()
    local ok, store = try(function() return content.magicEffects.records end)
    if not ok or store == nil then
        log('light: no magicEffects store')
        return
    end
    local rec
    for _, variant in ipairs({ LIGHT_EFFECT, string.lower(LIGHT_EFFECT) }) do
        local okr, found = try(function() return store[variant] end)
        if okr and found ~= nil then rec = found break end
    end
    if rec == nil then
        log('light: record not found')
        return
    end
    local okr, before = try(function() return rec.particle end)
    if not okr then
        log('light: particle field not readable')
        return
    end
    local okw = try(function() rec.particle = LIGHT_PARTICLE end)
    if not okw then
        log('light: write refused, particle stays ' .. tostring(before))
        return
    end
    local _, after = try(function() return rec.particle end)
    log('light: particle ' .. tostring(before) .. ' -> ' .. tostring(after))
end

local function run()
    local changed, skipped, failed = 0, 0, 0

    for _, target in ipairs(rules.targets) do
        local storeName = STORE[target[1]]
        local recordId, field = target[2], target[3]
        if storeName == nil then
            failed = failed + 1
        else
            local ok, store = try(function() return content[storeName].records end)
            if not ok or store == nil then
                failed = failed + 1
            else
                local rec, usedId = findRecord(store, recordId)
                if rec == nil then
                    skipped = skipped + 1
                elseif field == 'value' then
                    -- gameSettings maps an id straight to its value.
                    local newValue, hits = applyAll(tostring(rec), recordId)
                    if hits > 0 then
                        local okw = try(function() store[usedId] = newValue end)
                        if okw then changed = changed + 1 else failed = failed + 1 end
                    else
                        skipped = skipped + 1
                    end
                else
                    local okr, old = try(function() return rec[field] end)
                    if not okr or old == nil then
                        skipped = skipped + 1
                    else
                        local newValue, hits = applyAll(old, recordId)
                        if hits > 0 and #newValue <= #old then
                            local okw = try(function() rec[field] = newValue end)
                            if okw then changed = changed + 1 else failed = failed + 1 end
                        else
                            skipped = skipped + 1
                        end
                    end
                end
            end
        end
    end

    log('rules ' .. #rules.rules .. ', targets ' .. #rules.targets ..
        ', table ' .. rules.version)
    log('changed ' .. changed .. ', skipped ' .. skipped ..
        ', failed ' .. failed)
    if failed > 0 then
        log('WARNING: ' .. failed .. ' writes failed - check the API surface')
    end

    redirectLight()
end

return {
    engineHandlers = {
        onContentFilesLoaded = function()
            local ok, err = pcall(run)
            if not ok then log('FATAL: rewrite aborted: ' .. tostring(err)) end
        end,
    },
}
