#!/usr/bin/env python3
"""Build the mod from the rules table. Work Order 2, Architecture Part 14.

    python tools/scripts/transform.py                 # dry run, writes reports
    python tools/scripts/transform.py --write         # writes the artifacts too
    python tools/scripts/transform.py --profile momw --plugins <load order file>

Two emitters, one rules table, because the halves must not be able to drift:

  * **Lua half** - `mod/scripts/rewrite/rules.lua`, generated data read by the
    authored `apply.lua`. Substitution happens in the game at load time, so it
    lands on whatever text is in memory, including text another mod changed.
    That is what makes this half conflict-proof, and it is why the rules are
    shipped rather than the results.

  * **Plugin half** - `tools/build/scifi-rewrite.json`, ready for
    `tes3conv scifi-rewrite.json scifi-rewrite.esp`. A Morrowind plugin
    overrides a record whole, so each record is emitted complete with one field
    substituted.

The gates in check_rules.py run first and this refuses to write if any fail.
Nothing here performs a substitution of its own: the engine is shared with the
validator, so the preview and the artifact cannot disagree.
"""

import argparse
import collections
import csv
import hashlib
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from wo1_survey import (  # noqa: E402
    DISPLAY_FIELDS, FROZEN, LUA_TYPES, field_values, load_masters, record_key,
    stream_records,
)
from momw_compat import TYPE_CODE  # noqa: E402
import bodyparts  # noqa: E402
from check_rules import (  # noqa: E402
    apply_rules_keeping, load_frozen, load_rules, validate,
)
import effective  # noqa: E402

MASTERS = ("Morrowind.esm", "Tribunal.esm", "Bloodmoon.esm")

# Which content sub-package each record type lives in, from the 16 keys WO0
# enumerated at runtime. A type absent here has no load-context store and
# therefore belongs to the plugin half, whatever the rules table says.
LUA_STORE = {
    "BOOK": "books", "SPEL": "spells", "MISC": "miscs",
    "INGR": "ingredients", "GMST": "gameSettings",
    # content.magicEffects.records is a mutable list and the record carries
    # `description` as well as `name` - checked in core.lua before use. WO0
    # probed the name and it wrote; the description rides on the same store but
    # has not been seen on screen, so it is on the Gate 3 check list.
    "MGEF": "magicEffects",
}

# INFO records are only rewritten when they are uniquely filtered to an actor
# and are ordinary topic responses. Greetings, journals and general responses
# are frozen by policy - Architecture Part 5.
def info_is_writable(rec):
    speaker = str(rec.get("speaker_id", "") or "")
    dtype = str(rec.get("data", {}).get("dialogue_type", ""))
    return bool(speaker) and dtype == "Topic"


def lua_quote(text):
    """Long-bracket where possible, escaped short string otherwise."""
    if "]]" not in text and "\\" not in text:
        return "[[" + text + "]]"
    out = text.replace("\\", "\\\\").replace('"', '\\"')
    out = out.replace("\r", "\\r").replace("\n", "\\n")
    return '"' + out + '"'


def emit_lua_rules(rules, targets, table_hash, path):
    lines = [
        "-- GENERATED by tools/scripts/transform.py from tools/rules/naming.csv.",
        "-- Do not edit. Edit the rules table and re-run the transform.",
        f"-- Rules table sha256: {table_hash}",
        "",
        "return {",
        f"    version = {lua_quote(table_hash[:12])},",
        "    rules = {",
    ]
    for r in rules:
        excl = ""
        if r.exclude:
            # Quoted, not long-bracketed: `[` followed by `[[` is a long-bracket
            # opener in Lua, so [[[id]]] does not parse. Record ids are plain
            # ASCII identifiers, so a short string is safe here.
            items = ", ".join('["%s"] = true' % e.replace('"', '\\"')
                              for e in sorted(r.exclude))
            excl = f" exclude = {{ {items} }},"
        lines.append(
            "        { id = %s, pattern = %s, replacement = %s,"
            " left = %s, right = %s, case = %s,%s },"
            % (lua_quote(r.id), lua_quote(r.pattern), lua_quote(r.replacement),
               "true" if r.left else "false", "true" if r.right else "false",
               lua_quote(r.case), excl)
        )
    lines.append("    },")
    lines.append("    targets = {")
    for code, rid, field in targets:
        lines.append("        { %s, %s, %s },"
                     % (lua_quote(code), lua_quote(rid), lua_quote(field)))
    lines.append("    },")
    lines.append("}")
    with open(path, "w", encoding="ascii", newline="\n") as f:
        f.write("\n".join(lines) + "\n")


def load_authored(directory, frozen):
    """Records written by hand rather than derived from the rules.

    Some text cannot be produced by substitution at all - the book that explains
    what the words mean is the first case, since explaining a word and replacing
    it everywhere are opposite operations. Those records are written, kept beside
    a manifest, and emitted through the plugin, which overrides a record whole.

    An authored record must also be on the frozen list. If it were not, the
    rules would rewrite the very text that was written to escape them, and the
    two would fight silently on every build.
    """
    manifest = os.path.join(directory, "manifest.csv")
    if not os.path.exists(manifest):
        return []
    out = []
    with open(manifest, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            rid = row["record_id"].strip()
            path = os.path.join(directory, row["file"].strip())
            if not os.path.exists(path):
                raise SystemExit(f"authored text missing: {path}")
            with open(path, "r", encoding="ascii", newline="") as fh:
                text = fh.read()
            bad = [c for c in text if ord(c) > 127]
            if bad:
                raise SystemExit(f"{row['file']}: not ASCII: {bad[:5]!r}")
            if rid.lower() not in frozen:
                raise SystemExit(
                    f"{rid} is written by hand but is not in "
                    f"frozen-records.csv - the rules would rewrite it")
            out.append({"id": rid, "type": row["record_type"].strip(),
                        "field": row["field"].strip(), "text": text,
                        "file": row["file"].strip(),
                        # INFO records are identified by parent topic plus id,
                        # so an authored reply has to name its topic too.
                        "topic": (row.get("topic") or "").strip()})
    return out


def load_authored_dialogue(directory):
    """New topics and the replies under them, written by hand.

    Different from an authored record override: these records do not exist in
    the masters at all. A plugin may add them, and the format's one rule
    applies as it did to the overrides - an INFO belongs to the DIAL that
    precedes it, and the replies of one topic form a linked list through
    prev_id and next_id.

    Only actors who know answer. A topic with no matching INFO simply does not
    appear for that NPC, so the word explains itself where someone can explain
    it and stays silent everywhere else. That is characterisation done by the
    dialogue system rather than by prose.
    """
    manifest = os.path.join(directory, "manifest.csv")
    if not os.path.exists(manifest):
        return {}
    topics = collections.OrderedDict()
    with open(manifest, newline="", encoding="utf-8") as f:
        for row in sorted(csv.DictReader(f), key=lambda r: int(r["order"])):
            path = os.path.join(directory, row["file"].strip())
            if not os.path.exists(path):
                raise SystemExit(f"authored reply missing: {path}")
            with open(path, "r", encoding="ascii", newline="") as fh:
                text = fh.read().strip()
            bad = [c for c in text if ord(c) > 127]
            if bad:
                raise SystemExit(f"{row['file']}: not ASCII: {bad[:5]!r}")
            topics.setdefault(row["topic"].strip(), []).append(
                {"speaker": row["speaker_id"].strip(), "text": text,
                 "file": row["file"].strip()})
    return topics


def emit_authored_dialogue(topics):
    """DIAL record, then its replies, chained. Returns a flat record list."""
    out = []
    for topic, replies in topics.items():
        out.append({"type": "Dialogue", "flags": "", "id": topic,
                    "dialogue_type": "Topic"})
        ids = [f"{topic}_{i}" for i in range(1, len(replies) + 1)]
        for i, reply in enumerate(replies):
            out.append({
                "type": "DialogueInfo", "flags": "", "id": ids[i],
                "prev_id": ids[i - 1] if i else "",
                "next_id": ids[i + 1] if i + 1 < len(ids) else "",
                "data": {"dialogue_type": "Topic", "disposition": 0,
                         "speaker_rank": -1, "speaker_sex": "Any",
                         "player_rank": -1},
                "speaker_id": reply["speaker"], "speaker_race": "",
                "speaker_class": "", "speaker_faction": "", "speaker_cell": "",
                "player_faction": "", "sound_path": "", "text": reply["text"],
                "filters": [], "script_text": "",
            })
    return out


def full_records(json_paths, wanted):
    """Re-read the masters and keep the *complete* records the plugin needs.

    load_masters slims records down to the fields the survey reads, which is
    right for counting and wrong for emitting: a Morrowind plugin overrides a
    record whole, so a slimmed record produces a plugin missing half of every
    entry. tes3conv catches the most obvious case - "missing field `flags`" -
    and would happily have written the rest.

    Also collects the DIAL record for every topic we touch, and the order the
    INFO records appear in. An INFO belongs to the DIAL that precedes it in the
    file: emit the INFO without its DIAL and OpenMW refuses the record with
    "info record without dialog". Measured in game on 2026-08-28 - all 187
    dialogue records were rejected and the dialogue half simply did not exist.
    """
    out, dials, order = {}, {}, []
    for path in json_paths:
        topic = ""
        for rec in stream_records(path):
            if rec.get("type") == "Dialogue":
                topic = rec.get("id", "")
                dials[topic.lower()] = rec
            key = record_key(rec, topic)
            if key in wanted:
                out[key] = rec
                order.append((topic, key))
    return out, dials, order


def master_sizes(esm_dir):
    out = []
    for name in MASTERS:
        p = os.path.join(esm_dir, name)
        if not os.path.exists(p):
            raise SystemExit(f"master not found: {p}")
        out.append([name, os.path.getsize(p)])
    return out


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    root = os.path.abspath(os.path.join(here, "..", ".."))

    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--rules", default=os.path.join(root, "tools", "rules",
                                                    "naming.csv"))
    ap.add_argument("--frozen", default=os.path.join(root, "tools", "rules",
                                                     "frozen-records.csv"))
    ap.add_argument("--handwritten", default=os.path.join(root, "tools",
                                                          "handwritten"))
    ap.add_argument("--cache-dir", default=os.path.join(root, "tools", "cache"))
    ap.add_argument("--esm-dir", default=os.path.join(root, "tools", "input"))
    ap.add_argument("--out-mod", default=os.path.join(root, "mod"))
    ap.add_argument("--out-build", default=os.path.join(root, "tools", "build"))
    ap.add_argument("--out-reports", default=os.path.join(root, "tools",
                                                          "reports"))
    ap.add_argument("--profile", choices=["vanilla", "momw"], default="vanilla")
    ap.add_argument("--plugins", default=None,
                    help="momw profile: file listing the active load order")
    ap.add_argument("--tes3conv",
                    default=os.path.join(root, "tools", "bin", "tes3conv.exe"))
    ap.add_argument("--out-name", default="scifi-rewrite",
                    help="base name for the plugin artifacts")
    ap.add_argument("--write", action="store_true",
                    help="write the artifacts; without it this is a dry run")
    args = ap.parse_args()

    if args.profile == "momw" and not args.plugins:
        raise SystemExit(
            "--profile momw needs --plugins: the effective record set is the\n"
            "masters plus the active load order, and there is no openmw.cfg in\n"
            "the mod directory to read it from. Generating from the bare\n"
            "masters under this profile would silently revert Patch for\n"
            "Purists in 13 dialogue records - tools/reports/momw-compat.md."
        )

    raw = open(args.rules, "rb").read()
    table_hash = hashlib.sha256(raw).hexdigest()
    rules = load_rules(args.rules)
    errors, warnings = validate(rules)
    for w in warnings:
        print("  warning:", w)
    if errors:
        for e in errors:
            print("  REFUSED:", e)
        raise SystemExit(f"{len(errors)} rule violations - refusing to run")
    frozen = load_frozen(args.frozen)
    print(f"Rules: {len(rules)}, table sha256 {table_hash[:12]}")
    print(f"Frozen records, hand-written instead: {len(frozen)}")
    for rid in sorted(frozen):
        print(f"    {frozen[rid]['record_type']} {frozen[rid]['record_id']}")

    paths = [os.path.join(args.cache_dir, n.replace(".esm", ".json"))
             for n in MASTERS]
    for p in paths:
        if not os.path.exists(p):
            raise SystemExit(f"missing {p} - run tools/scripts/wo1_survey.py")
    authored = load_authored(args.handwritten, frozen)
    print(f"Records written by hand: {len(authored)}")
    new_topics = load_authored_dialogue(os.path.join(args.handwritten,
                                                     "dialogue"))
    for topic, replies in new_topics.items():
        print(f"New topic '{topic}': {len(replies)} replies from "
              f"{', '.join(r['speaker'] for r in replies)}")

    records = load_masters(paths)

    # Under the momw profile the record a player reads is not the master's. A
    # plugin overrides a record whole, so the last plugin to define one holds
    # everything about it - text, mesh, icon. Take the winner's version before
    # substituting, or the rebuild silently strips other people's work.
    overrides = {}
    if args.profile == "momw":
        data_dirs, content = effective.parse_cfg(args.plugins)
        plugins, missing = effective.resolve(content, data_dirs)
        if missing:
            raise SystemExit(f"{len(missing)} content files not found on disk: "
                             f"{missing[:3]}")
        # Never scan our own output. Once the plugin is installed it sits last
        # in the load order, so it wins every record it defines - and those
        # records are already converted. The build would then read `Zenar` back
        # as the effective text, match no rule against it, and emit a plugin
        # with the renames missing. It ate itself exactly once: 327 records
        # defined-last by a mod became 519, and the plugin collapsed from 347
        # records to 21. Nothing warned, because every step succeeded.
        mine = os.path.normcase(os.path.abspath(args.out_build))
        ours = [n for n, path in plugins
                if os.path.normcase(os.path.abspath(path)).startswith(mine)]
        if ours:
            plugins = [(n, path) for n, path in plugins
                       if os.path.normcase(os.path.abspath(path)).startswith(mine)
                       is False]
            print(f"Excluded from the scan, because it is ours: "
                  f"{', '.join(ours)}")
        print(f"Load order: {len(plugins)} plugin files from {args.plugins}")
        master_names = {m.lower() for m in MASTERS}
        # Only the records a rule could possibly touch. Scanning for all 60,000
        # would drag half the mod list through tes3conv for nothing.
        wanted_keys = set()
        for key, rec in records.items():
            specs = DISPLAY_FIELDS.get(rec["type"])
            if not specs:
                continue
            for spec in specs:
                if (rec["type"], spec) in FROZEN:
                    continue
                for value in field_values(rec, spec):
                    low = value.lower()
                    if any(r.pattern.lower() in low for r in rules):
                        wanted_keys.add(key)
                        break
        # Authored records are touched whether or not a rule matches them -
        # Vivec's confession contains no keyword at all - so they have to join
        # the scan explicitly. Missed here, the build inherits the master's
        # version of the record and quietly drops whatever a mod changed in it.
        # Caught by verify_momw.py: his filters came from Morrowind.esm while
        # Patch for Purists had edited them.
        type_name_pre = {v: k for k, v in TYPE_CODE.items()}
        for a in authored:
            if a["type"] == "INFO":
                wanted_keys.add(("DialogueInfo", a["topic"].lower(),
                                 a["id"].lower()))
            else:
                wanted_keys.add((type_name_pre[a["type"]], a["id"].lower()))
        print(f"  records a rule could touch, plus authored: "
              f"{len(wanted_keys)}")
        print("  scanning for overrides ...")
        winners = effective.find_winners(plugins, wanted_keys)
        foreign = {k: v for k, v in winners.items()
                   if os.path.basename(v).lower() not in master_names}
        print(f"  records a mod defines last: {len(foreign)}")
        converted = effective.convert(set(foreign.values()), args.cache_dir,
                                      args.tes3conv)
        by_plugin = collections.defaultdict(set)
        for key, path in foreign.items():
            by_plugin[path].add(key)
        for path, keys in by_plugin.items():
            overrides.update(effective.read_records(converted[path], keys))
        print(f"  effective records taken from mods: {len(overrides)}")
        for key, rec in overrides.items():
            records[key] = rec

    lua_targets = []
    plugin_records = collections.OrderedDict()
    rows = []
    counts = collections.Counter()

    for key, rec in records.items():
        rtype = rec["type"]
        specs = DISPLAY_FIELDS.get(rtype)
        if not specs:
            continue
        code = TYPE_CODE.get(rtype)
        if code is None:
            continue
        # MagicEffect keys on effect_id and Skill on skill_id, so the target
        # list would otherwise ship empty ids for those stores.
        rid = str(rec.get("id") or rec.get("effect_id")
                  or rec.get("skill_id") or rec.get("name") or "")
        route = "lua" if rtype in LUA_TYPES else "plugin"
        if route == "lua" and code not in LUA_STORE:
            route = "plugin"
        for spec in specs:
            if (rtype, spec) in FROZEN:
                continue
            if code == "INFO" and not info_is_writable(rec):
                counts["info_frozen_by_policy"] += 1
                continue
            field = spec.split(".")[0] if "." in spec else spec
            # A dialogue response hyperlinks a topic only where the topic's
            # word appears literally. Rewriting every occurrence silently kills
            # the link, and 21 of the 193 rewritten lines did exactly that
            # before this was measured.
            keep = rec.get("topic", "") if code == "INFO" else ""
            for value in field_values(rec, spec):
                new, applied, notes, protected, kept = apply_rules_keeping(
                    value, rules, code, field, rid, keep, frozen)
                if kept:
                    counts["topic_keyword_kept"] += 1
                counts["protected_in_markup"] += len(protected)
                if not applied:
                    continue
                counts[f"{route}_fields"] += 1
                low_keep = (keep or "").lower()
                rows.append({
                    "route": route, "record_type": code, "record_id": rid,
                    "field": field,
                    "rules": " ".join(sorted({a[0] for a in applied})),
                    "substitutions": len(applied),
                    "length_delta": len(new) - len(value),
                    "topic": keep,
                    "topic_keyword_before":
                        value.lower().count(low_keep) if low_keep else 0,
                    "topic_keyword_after":
                        new.lower().count(low_keep) if low_keep else 0,
                })
                if route == "lua":
                    lua_targets.append((code, rid, field))
                    # A magic effect's NAME is not a record field in the ESM -
                    # the engine builds it from a GMST at load, in
                    # esmfallbacks.lua, which runs before our script. Rewriting
                    # the GMST is therefore too late for the name: measured in
                    # game, the spell read "Summon Zenaroth" while its effect
                    # line still read "Summon Daedroth". So the effect name is
                    # written directly as well, on top of what the fallback
                    # copied. The GMST rewrite stays - it is what the tooltip
                    # header and the spellmaker use.
                    if code == "GMST" and rid.startswith("sEffect"):
                        lua_targets.append(("MGEF", rid[len("sEffect"):],
                                            "name"))
                else:
                    plugin_records.setdefault(key, {})[spec] = new

    # Authored records join the plugin side. They carry no rule ids, because no
    # rule produced them.
    type_name = {v: k for k, v in TYPE_CODE.items()}
    for a in authored:
        if a["type"] == "INFO":
            if not a["topic"]:
                raise SystemExit(f"{a['id']}: an authored INFO needs a topic")
            key = ("DialogueInfo", a["topic"].lower(), a["id"].lower())
        else:
            key = (type_name[a["type"]], a["id"].lower())
        if key not in records:
            raise SystemExit(f"authored record not in the masters: {a['id']}")
        old = records[key].get(a["field"], "") or ""
        plugin_records.setdefault(key, {})[a["field"]] = a["text"]
        rows.append({
            "route": "plugin", "record_type": a["type"], "record_id": a["id"],
            "field": a["field"], "rules": "HAND-WRITTEN",
            "substitutions": 0, "length_delta": len(a["text"]) - len(old),
            "topic": "", "topic_keyword_before": 0, "topic_keyword_after": 0,
        })
        print(f"    {a['type']} {a['id']}: {len(old)} -> {len(a['text'])} bytes"
              f"  ({a['file']})")

    print(f"Lua half   : {counts['lua_fields']} record-fields, "
          f"{len(lua_targets)} targets")
    print(f"Plugin half: {counts['plugin_fields']} record-fields, "
          f"{len(plugin_records)} records")
    print(f"INFO frozen by dialogue policy: {counts['info_frozen_by_policy']}")
    print(f"Matches protected inside markup: {counts['protected_in_markup']}")
    print(f"Topic keywords kept so the hyperlink still fires: "
          f"{counts['topic_keyword_kept']}")

    broken = [r for r in rows if r["topic_keyword_before"] > 0
              and r["topic_keyword_after"] == 0]
    if broken:
        for r in broken[:5]:
            print("  REFUSED: lost its topic link:", r["record_id"], r["topic"])
        raise SystemExit(f"{len(broken)} records lost their topic hyperlink")

    # The length rule protects UI fields from overflow, and it binds every
    # substitution. A hand-written book is a different animal: book text
    # paginates, so it may run longer than vanilla on purpose. The exemption is
    # narrow - authored NAME and DESCRIPTION fields still have to fit.
    grew = [r for r in rows
            if r["length_delta"] > 0
            and not (r["rules"] == "HAND-WRITTEN" and r["field"] == "text")]
    if grew:
        for r in grew[:5]:
            print("  REFUSED: grew:", r)
        raise SystemExit(f"{len(grew)} fields grew - refusing to write")

    os.makedirs(args.out_reports, exist_ok=True)
    diff_path = os.path.join(args.out_reports, "transform-diff.csv")
    with open(diff_path, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)
    print("Wrote", os.path.relpath(diff_path, root))

    if not args.write:
        print("\nDry run. Pass --write to emit the artifacts.")
        return 0

    lua_dir = os.path.join(args.out_mod, "scripts", "rewrite")
    os.makedirs(lua_dir, exist_ok=True)
    rules_lua = os.path.join(lua_dir, "rules.lua")
    emit_lua_rules(rules, lua_targets, table_hash, rules_lua)
    print("Wrote", os.path.relpath(rules_lua, root))

    omwscripts = os.path.join(args.out_mod, "scifi-rewrite.omwscripts")
    with open(omwscripts, "w", encoding="ascii", newline="\n") as f:
        f.write("# Sci-fi conversion, Lua half. Generated targets live in\n"
                "# scripts/rewrite/rules.lua; the code is scripts/rewrite/apply.lua.\n"
                "#\n"
                "# topic.lua makes the word Zenar clickable by adding the topic to\n"
                "# the player. The topic and its answers come from the plugin, so\n"
                "# only actors who know it can answer.\n"
                "\n"
                "LOAD:   scripts/rewrite/apply.lua\n"
                "PLAYER: scripts/rewrite/topic.lua\n")
    print("Wrote", os.path.relpath(omwscripts, root))

    os.makedirs(args.out_build, exist_ok=True)
    header = {
        "type": "Header", "flags": "", "version": 1.3, "file_type": "Esp",
        "author": "Morrowind SciFi Conversion",
        "description": f"Generated by transform.py from naming.csv "
                       f"{table_hash[:12]}",
        "num_objects": len(plugin_records),
        "masters": master_sizes(args.esm_dir),
    }
    print("Re-reading the masters for complete plugin records ...")
    full, dials, order = full_records(paths, set(plugin_records))
    # Where a mod defines the record last, that is the record to emit. Taking
    # the master's version here would hand back a plugin that strips their mesh,
    # their icon and their typo fixes while claiming only to rename a thing.
    for key, rec in overrides.items():
        if key in full:
            full[key] = rec
    missing = set(plugin_records) - set(full)
    if missing:
        raise SystemExit(f"{len(missing)} plugin records could not be re-read: "
                         f"{sorted(missing)[:3]}")
    def edited(key):
        rec = dict(full[key])
        for spec, value in plugin_records[key].items():
            if "." in spec:
                head, tail = spec.split(".", 1)
                node = dict(rec.get(head) or {})
                node[tail] = value
                rec[head] = node
            else:
                rec[spec] = value
        return rec

    out = [header]
    # Everything that is not dialogue, in any order.
    for key in plugin_records:
        if key[0] != "DialogueInfo":
            out.append(edited(key))

    # Dialogue, grouped: each DIAL record followed by its own INFO records, in
    # the order the masters have them. This is what the format requires and
    # what the first game run proved by rejecting all 187 records.
    grouped = collections.OrderedDict()
    for topic, key in order:
        if key[0] == "DialogueInfo":
            grouped.setdefault(topic, [])
            if key not in grouped[topic]:
                grouped[topic].append(key)
    emitted_dial = 0
    for topic, keys in grouped.items():
        dial = dials.get(topic.lower())
        if dial is None:
            raise SystemExit(f"no DIAL record found for topic {topic!r}")
        out.append(dial)
        emitted_dial += 1
        for key in keys:
            out.append(edited(key))
    # Topics we invented, with their replies. Added last: they depend on
    # nothing in the masters and nothing depends on them.
    new_records = emit_authored_dialogue(new_topics)
    out.extend(new_records)

    # The imported armour. A mesh in a data directory is invisible until a
    # bodypart record names it and an armour record names that, so both hops
    # are made here - and only for pieces that are actually built, because a
    # record naming a missing mesh shows as nothing at all.
    built = bodyparts.on_disk(os.path.join(args.out_build,
                                           f"armour-{args.profile}",
                                           "Meshes", "zenar"))
    if built:
        moved = sum(bodyparts.repoint(r, built) for r in out
                    if r.get("type") == "Armor")
        parts = bodyparts.emit(built=built)
        out.extend(parts)
        print(f"Imported armour: {len(parts)} bodyparts, "
              f"{moved} armour slots repointed "
              f"({', '.join(sorted(built))})")
    else:
        print("Imported armour: no built meshes found, nothing repointed")

    header["num_objects"] = len(out) - 1
    print(f"  {emitted_dial} topic records emitted to own "
          f"{sum(len(v) for v in grouped.values())} dialogue records")
    plugin_path = os.path.join(args.out_build, args.out_name + ".json")
    with open(plugin_path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(out, f, indent=2, ensure_ascii=False)
    print("Wrote", os.path.relpath(plugin_path, root))
    print("\nConvert with:")
    print(f"  tools/bin/tes3conv.exe {os.path.relpath(plugin_path, root)} "
          f"tools/build/scifi-rewrite.esp")
    return 0


if __name__ == "__main__":
    sys.exit(main())
