#!/usr/bin/env python3
"""Build the mod from the rules table. Work Order 2, Architecture Part 14.

    python tools/scripts/transform.py                 # dry run, writes reports
    python tools/scripts/transform.py --write         # writes the artifacts too
    python tools/scripts/transform.py --profile momw --plugins <load order file>

Two emitters, one rules table, because the halves must not be able to drift:

  * **Lua half** - `mod/scripts/rewrite/rules.lua`, generated data read by the
    authored `apply.lua`. Substitution happens in the game at load time, so it
    lands on whatever text is in memory, including text another mod changed.
    That is what makes this half conflict-proof, and it is why the rules are
    shipped rather than the results.

  * **Plugin half** - `tools/build/scifi-rewrite.json`, ready for
    `tes3conv scifi-rewrite.json scifi-rewrite.esp`. A Morrowind plugin
    overrides a record whole, so each record is emitted complete with one field
    substituted.

The gates in check_rules.py run first and this refuses to write if any fail.
Nothing here performs a substitution of its own: the engine is shared with the
validator, so the preview and the artifact cannot disagree.
"""

import argparse
import collections
import csv
import hashlib
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from wo1_survey import (  # noqa: E402
    DISPLAY_FIELDS, FROZEN, LUA_TYPES, field_values, load_masters, record_key,
    stream_records,
)
from momw_compat import TYPE_CODE  # noqa: E402
from check_rules import apply_rules, load_rules, validate  # noqa: E402

MASTERS = ("Morrowind.esm", "Tribunal.esm", "Bloodmoon.esm")

# Which content sub-package each record type lives in, from the 16 keys WO0
# enumerated at runtime. A type absent here has no load-context store and
# therefore belongs to the plugin half, whatever the rules table says.
LUA_STORE = {
    "BOOK": "books", "SPEL": "spells", "MISC": "miscs",
    "INGR": "ingredients", "GMST": "gameSettings",
    # content.magicEffects.records is a mutable list and the record carries
    # `description` as well as `name` - checked in core.lua before use. WO0
    # probed the name and it wrote; the description rides on the same store but
    # has not been seen on screen, so it is on the Gate 3 check list.
    "MGEF": "magicEffects",
}

# INFO records are only rewritten when they are uniquely filtered to an actor
# and are ordinary topic responses. Greetings, journals and general responses
# are frozen by policy - Architecture Part 5.
def info_is_writable(rec):
    speaker = str(rec.get("speaker_id", "") or "")
    dtype = str(rec.get("data", {}).get("dialogue_type", ""))
    return bool(speaker) and dtype == "Topic"


def lua_quote(text):
    """Long-bracket where possible, escaped short string otherwise."""
    if "]]" not in text and "\\" not in text:
        return "[[" + text + "]]"
    out = text.replace("\\", "\\\\").replace('"', '\\"')
    out = out.replace("\r", "\\r").replace("\n", "\\n")
    return '"' + out + '"'


def emit_lua_rules(rules, targets, table_hash, path):
    lines = [
        "-- GENERATED by tools/scripts/transform.py from tools/rules/naming.csv.",
        "-- Do not edit. Edit the rules table and re-run the transform.",
        f"-- Rules table sha256: {table_hash}",
        "",
        "return {",
        f"    version = {lua_quote(table_hash[:12])},",
        "    rules = {",
    ]
    for r in rules:
        excl = ""
        if r.exclude:
            # Quoted, not long-bracketed: `[` followed by `[[` is a long-bracket
            # opener in Lua, so [[[id]]] does not parse. Record ids are plain
            # ASCII identifiers, so a short string is safe here.
            items = ", ".join('["%s"] = true' % e.replace('"', '\\"')
                              for e in sorted(r.exclude))
            excl = f" exclude = {{ {items} }},"
        lines.append(
            "        { id = %s, pattern = %s, replacement = %s,"
            " left = %s, right = %s, case = %s,%s },"
            % (lua_quote(r.id), lua_quote(r.pattern), lua_quote(r.replacement),
               "true" if r.left else "false", "true" if r.right else "false",
               lua_quote(r.case), excl)
        )
    lines.append("    },")
    lines.append("    targets = {")
    for code, rid, field in targets:
        lines.append("        { %s, %s, %s },"
                     % (lua_quote(code), lua_quote(rid), lua_quote(field)))
    lines.append("    },")
    lines.append("}")
    with open(path, "w", encoding="ascii", newline="\n") as f:
        f.write("\n".join(lines) + "\n")


def full_records(json_paths, wanted):
    """Re-read the masters and keep the *complete* records the plugin needs.

    load_masters slims records down to the fields the survey reads, which is
    right for counting and wrong for emitting: a Morrowind plugin overrides a
    record whole, so a slimmed record produces a plugin missing half of every
    entry. tes3conv catches the most obvious case - "missing field `flags`" -
    and would happily have written the rest.
    """
    out = {}
    for path in json_paths:
        topic = ""
        for rec in stream_records(path):
            if rec.get("type") == "Dialogue":
                topic = rec.get("id", "")
            key = record_key(rec, topic)
            if key in wanted:
                out[key] = rec
    return out


def master_sizes(esm_dir):
    out = []
    for name in MASTERS:
        p = os.path.join(esm_dir, name)
        if not os.path.exists(p):
            raise SystemExit(f"master not found: {p}")
        out.append([name, os.path.getsize(p)])
    return out


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    root = os.path.abspath(os.path.join(here, "..", ".."))

    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--rules", default=os.path.join(root, "tools", "rules",
                                                    "naming.csv"))
    ap.add_argument("--cache-dir", default=os.path.join(root, "tools", "cache"))
    ap.add_argument("--esm-dir", default=os.path.join(root, "tools", "input"))
    ap.add_argument("--out-mod", default=os.path.join(root, "mod"))
    ap.add_argument("--out-build", default=os.path.join(root, "tools", "build"))
    ap.add_argument("--out-reports", default=os.path.join(root, "tools",
                                                          "reports"))
    ap.add_argument("--profile", choices=["vanilla", "momw"], default="vanilla")
    ap.add_argument("--plugins", default=None,
                    help="momw profile: file listing the active load order")
    ap.add_argument("--write", action="store_true",
                    help="write the artifacts; without it this is a dry run")
    args = ap.parse_args()

    if args.profile == "momw" and not args.plugins:
        raise SystemExit(
            "--profile momw needs --plugins: the effective record set is the\n"
            "masters plus the active load order, and there is no openmw.cfg in\n"
            "the mod directory to read it from. Generating from the bare\n"
            "masters under this profile would silently revert Patch for\n"
            "Purists in 13 dialogue records - tools/reports/momw-compat.md."
        )

    raw = open(args.rules, "rb").read()
    table_hash = hashlib.sha256(raw).hexdigest()
    rules = load_rules(args.rules)
    errors, warnings = validate(rules)
    for w in warnings:
        print("  warning:", w)
    if errors:
        for e in errors:
            print("  REFUSED:", e)
        raise SystemExit(f"{len(errors)} rule violations - refusing to run")
    print(f"Rules: {len(rules)}, table sha256 {table_hash[:12]}")

    paths = [os.path.join(args.cache_dir, n.replace(".esm", ".json"))
             for n in MASTERS]
    for p in paths:
        if not os.path.exists(p):
            raise SystemExit(f"missing {p} - run tools/scripts/wo1_survey.py")
    records = load_masters(paths)

    lua_targets = []
    plugin_records = collections.OrderedDict()
    rows = []
    counts = collections.Counter()

    for key, rec in records.items():
        rtype = rec["type"]
        specs = DISPLAY_FIELDS.get(rtype)
        if not specs:
            continue
        code = TYPE_CODE.get(rtype)
        if code is None:
            continue
        # MagicEffect keys on effect_id and Skill on skill_id, so the target
        # list would otherwise ship empty ids for those stores.
        rid = str(rec.get("id") or rec.get("effect_id")
                  or rec.get("skill_id") or rec.get("name") or "")
        route = "lua" if rtype in LUA_TYPES else "plugin"
        if route == "lua" and code not in LUA_STORE:
            route = "plugin"
        for spec in specs:
            if (rtype, spec) in FROZEN:
                continue
            if code == "INFO" and not info_is_writable(rec):
                counts["info_frozen_by_policy"] += 1
                continue
            field = spec.split(".")[0] if "." in spec else spec
            for value in field_values(rec, spec):
                new, applied, notes, protected = apply_rules(
                    value, rules, code, field, rid)
                counts["protected_in_markup"] += len(protected)
                if not applied:
                    continue
                counts[f"{route}_fields"] += 1
                rows.append({
                    "route": route, "record_type": code, "record_id": rid,
                    "field": field,
                    "rules": " ".join(sorted({a[0] for a in applied})),
                    "substitutions": len(applied),
                    "length_delta": len(new) - len(value),
                })
                if route == "lua":
                    lua_targets.append((code, rid, field))
                else:
                    plugin_records.setdefault(key, {})[spec] = new

    print(f"Lua half   : {counts['lua_fields']} record-fields, "
          f"{len(lua_targets)} targets")
    print(f"Plugin half: {counts['plugin_fields']} record-fields, "
          f"{len(plugin_records)} records")
    print(f"INFO frozen by dialogue policy: {counts['info_frozen_by_policy']}")
    print(f"Matches protected inside markup: {counts['protected_in_markup']}")

    grew = [r for r in rows if r["length_delta"] > 0]
    if grew:
        for r in grew[:5]:
            print("  REFUSED: grew:", r)
        raise SystemExit(f"{len(grew)} fields grew - refusing to write")

    os.makedirs(args.out_reports, exist_ok=True)
    diff_path = os.path.join(args.out_reports, "transform-diff.csv")
    with open(diff_path, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)
    print("Wrote", os.path.relpath(diff_path, root))

    if not args.write:
        print("\nDry run. Pass --write to emit the artifacts.")
        return 0

    lua_dir = os.path.join(args.out_mod, "scripts", "rewrite")
    os.makedirs(lua_dir, exist_ok=True)
    rules_lua = os.path.join(lua_dir, "rules.lua")
    emit_lua_rules(rules, lua_targets, table_hash, rules_lua)
    print("Wrote", os.path.relpath(rules_lua, root))

    omwscripts = os.path.join(args.out_mod, "scifi-rewrite.omwscripts")
    with open(omwscripts, "w", encoding="ascii", newline="\n") as f:
        f.write("# Sci-fi conversion, Lua half. Generated targets live in\n"
                "# scripts/rewrite/rules.lua; the code is scripts/rewrite/apply.lua.\n\n"
                "LOAD: scripts/rewrite/apply.lua\n")
    print("Wrote", os.path.relpath(omwscripts, root))

    os.makedirs(args.out_build, exist_ok=True)
    header = {
        "type": "Header", "flags": "", "version": 1.3, "file_type": "Esp",
        "author": "Morrowind SciFi Conversion",
        "description": f"Generated by transform.py from naming.csv "
                       f"{table_hash[:12]}",
        "num_objects": len(plugin_records),
        "masters": master_sizes(args.esm_dir),
    }
    print("Re-reading the masters for complete plugin records ...")
    full = full_records(paths, set(plugin_records))
    missing = set(plugin_records) - set(full)
    if missing:
        raise SystemExit(f"{len(missing)} plugin records could not be re-read: "
                         f"{sorted(missing)[:3]}")
    out = [header]
    for key, edits in plugin_records.items():
        rec = dict(full[key])
        for spec, value in edits.items():
            if "." in spec:
                head, tail = spec.split(".", 1)
                node = dict(rec.get(head) or {})
                node[tail] = value
                rec[head] = node
            else:
                rec[spec] = value
        out.append(rec)
    plugin_path = os.path.join(args.out_build, "scifi-rewrite.json")
    with open(plugin_path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(out, f, indent=2, ensure_ascii=False)
    print("Wrote", os.path.relpath(plugin_path, root))
    print("\nConvert with:")
    print(f"  tools/bin/tes3conv.exe {os.path.relpath(plugin_path, root)} "
          f"tools/build/scifi-rewrite.esp")
    return 0


if __name__ == "__main__":
    sys.exit(main())
